# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Build

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "yarn.lock"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::395594542180:role/github-actions-deploy
          aws-region: us-east-1
  
      - name: Install Top Level Dependencies
        run: yarn install

      - name: Install Edge Dependencies
        run: yarn install

      - name: Build dev
        run: yarn build:dev

      - name: Build Edge
        run: |
          pushd edge
          yarn build
          popd
        